# Generated by Django 2.0.7 on 2018-07-16 19:18

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(max_length=180, validators=[tweets.validators.validate_content]),
        ),
    ]
